--[[


local txd = engineLoadTXD("int/pod_suf_tex.txd")
			engineImportTXD(txd, 16747)
local dff = engineLoadDFF("int/pod_suf_biale.dff", 16747)
			engineReplaceModel(dff, 16747)
local col = engineLoadCOL ("int/pod_suf_col.col" )
			engineReplaceCOL ( col, 16747)

local txd = engineLoadTXD("int/pod_suf_tex.txd")
			engineImportTXD(txd, 16746)
local dff = engineLoadDFF("int/pod_suf_dyw.dff", 16746)
			engineReplaceModel(dff, 16746)
local col = engineLoadCOL ("int/pod_suf_col.col" )
			engineReplaceCOL ( col, 16746)
--------------------------------------------------------------
local txd = engineLoadTXD("int/pod_suf_tex.txd")
			engineImportTXD(txd, 16745)
local dff = engineLoadDFF("int/pod_suf_dyw2.dff", 16745)
			engineReplaceModel(dff, 16745)
local col = engineLoadCOL ("int/pod_suf_col.col" )
			engineReplaceCOL ( col, 16745)
--------------------------------------------------------------
local txd = engineLoadTXD("int/pod_suf_tex.txd")
			engineImportTXD(txd, 16744)
local dff = engineLoadDFF("int/pod_suf_pan.dff", 16744)
			engineReplaceModel(dff, 16744)
local col = engineLoadCOL ("int/pod_suf_col.col" )
			engineReplaceCOL ( col, 16744)
--------------------------------------------------------------
local txd = engineLoadTXD("int/pod_suf_tex.txd")
			engineImportTXD(txd, 16743)
local dff = engineLoadDFF("int/pod_suf_pan2.dff", 16743)
			engineReplaceModel(dff, 16743)
local col = engineLoadCOL ("int/pod_suf_col.col" )
			engineReplaceCOL ( col, 16743)
--------------------------------------------------------------
local txd = engineLoadTXD("int/pod_suf_tex.txd")
			engineImportTXD(txd, 16742)
local dff = engineLoadDFF("int/pod_suf_plytki.dff", 16742)
			engineReplaceModel(dff, 16742)
local col = engineLoadCOL ("int/pod_suf_col.col" )
			engineReplaceCOL ( col, 16742)
--------------------------------------------------------------
local txd = engineLoadTXD("int/pod_suf_tex.txd")
			engineImportTXD(txd, 16741)
local dff = engineLoadDFF("int/pod_suf_plytki2.dff", 16741)
			engineReplaceModel(dff, 16741)
local col = engineLoadCOL ("int/pod_suf_col.col" )
			engineReplaceCOL ( col, 16741)
--------------------------------------------------------------
local txd = engineLoadTXD("int/pod_suf_tex.txd")
			engineImportTXD(txd, 16740)
local dff = engineLoadDFF("int/pod_suf_plytki3.dff", 16740)
			engineReplaceModel(dff, 16740)
local col = engineLoadCOL ("int/pod_suf_col.col" )
			engineReplaceCOL ( col, 16740)
--------------------------------------------------------------
local txd = engineLoadTXD("int/sciana_drzwi_okno_tex.txd")
			engineImportTXD(txd, 10229)
local dff = engineLoadDFF("int/sciana_biala.dff", 10229)
			engineReplaceModel(dff, 10229)
local col = engineLoadCOL ("int/sciana_col.col" )
			engineReplaceCOL ( col, 10229)
--------------------------------------------------------------
local txd = engineLoadTXD("int/sciana_drzwi_okno_tex.txd")
			engineImportTXD(txd, 10230)
local dff = engineLoadDFF("int/sciana_blekitna.dff", 10230)
			engineReplaceModel(dff, 10230)
local col = engineLoadCOL ("int/sciana_col.col" )
			engineReplaceCOL ( col, 10230)
--------------------------------------------------------------
local txd = engineLoadTXD("int/sciana_drzwi_okno_tex.txd")
			engineImportTXD(txd, 10231)
local dff = engineLoadDFF("int/sciana_zielona.dff", 10231)
			engineReplaceModel(dff, 10231)
local col = engineLoadCOL ("int/sciana_col.col" )
			engineReplaceCOL ( col, 10231)
--------------------------------------------------------------
local txd = engineLoadTXD("int/sciana_drzwi_okno_tex.txd")
			engineImportTXD(txd, 10228)
local dff = engineLoadDFF("int/sciana_kremowa.dff", 10228)
			engineReplaceModel(dff, 10228)
local col = engineLoadCOL ("int/sciana_col.col" )
			engineReplaceCOL ( col, 10228)
--------------------------------------------------------------
local txd = engineLoadTXD("int/sciana_drzwi_okno_tex.txd")
			engineImportTXD(txd, 10227)
local dff = engineLoadDFF("int/sciana_drzwi_biala.dff", 10227)
			engineReplaceModel(dff, 10227)
local col = engineLoadCOL ("int/sciana_drzwi_col.col" )
			engineReplaceCOL ( col, 10227)
--------------------------------------------------------------
local txd = engineLoadTXD("int/sciana_drzwi_okno_tex.txd")
			engineImportTXD(txd, 16739)
local dff = engineLoadDFF("int/sciana_drzwi_blekitna.dff", 16739)
			engineReplaceModel(dff, 16739)
local col = engineLoadCOL ("int/sciana_drzwi_col.col" )
			engineReplaceCOL ( col, 16739)
--------------------------------------------------------------
local txd = engineLoadTXD("int/sciana_drzwi_okno_tex.txd")
			engineImportTXD(txd, 16738)
local dff = engineLoadDFF("int/sciana_drzwi_zielona.dff", 16738)
			engineReplaceModel(dff, 16738)
local col = engineLoadCOL ("int/sciana_drzwi_col.col" )
			engineReplaceCOL ( col, 16738)
--------------------------------------------------------------

]]--